import { getStaticSrc } from './helper';

export interface AudioObj {
  name: string;
  enable: boolean;
  type: string;
  group: string[];
  src: string;
  content?: string;
}
export type AudioData = AudioObj[];

export const AudioData: AudioData = [
  { name: 'click', enable: true, type: 'basic', group: ['basic'], src: 'audios/basic/click.mp3' },
  { name: 'raise', enable: true, type: 'basic', group: ['basic'], src: 'audios/basic/raise.mp3' },
  { name: 'fold', enable: true, type: 'basic', group: ['basic'], src: 'audios/basic/fold.mp3' },
  { name: 'income', enable: true, type: 'basic', group: ['income'], src: 'audios/basic/income.mp3' },
  {
    name: 'raise-ms-xiaoxiao-raise',
    enable: true,
    type: 'simple',
    group: ['raise'],
    src: 'audios/simple/raise-ms-xiaoxiao-raise.mp3',
  },
  {
    name: 'raise-ms-xiaobei-dani',
    enable: true,
    type: 'simple',
    group: ['raise'],
    src: 'audios/simple/raise-ms-xiaobei-dani.mp3',
    content: '大你',
  },
  {
    name: 'allin-ms-xiaoxiao-allin',
    enable: true,
    type: 'simple',
    group: ['allin'],
    src: 'audios/simple/allin-ms-xiaoxiao-allin.mp3',
  },
  {
    name: 'standup-ms-xiaoxiao-goodbye1',
    enable: true,
    type: 'simple',
    group: ['standup'],
    src: 'audios/simple/standup-ms-xiaoxiao-goodbye1.mp3',
    content: '牌友们, 走先啦',
  },
  {
    name: 'standup-ms-xiaoxiao-goodbye2',
    enable: true,
    type: 'simple',
    group: ['standup'],
    src: 'audios/simple/standup-ms-xiaoxiao-goodbye2.mp3',
    content: '嘿嘿嘿, 赢了, 走人啦',
  },
  {
    name: 'standup-ms-xiaobei-goodbye3',
    enable: true,
    type: 'simple',
    group: ['standup'],
    src: 'audios/simple/standup-ms-xiaobei-goodbye3.mp3',
    content: '欺负人, 不和你们玩了!!!',
  },
  {
    name: 'game-start',
    enable: true,
    type: 'dialogue',
    group: ['gameStart'],
    src: 'audios/dialogue/世界赌神大赛 正式开始.mp3',
    content: '世界赌神大赛 正式开始',
  },
  {
    name: 'audio01',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/199万.mp3',
    content: '200万',
  },
  {
    name: 'audio02',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/show晒啦无讲甘多.mp3',
    content: 'show晒啦无讲甘多',
  },
  {
    name: 'audio03',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/一千大三千万.mp3',
    content: '一千大三千万',
  },
  {
    name: 'audio04',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/七百万 晒你冷.mp3',
    content: '七百万 晒你冷',
  },
  {
    name: 'audio05',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/三百万呐.mp3',
    content: '三百万呐',
  },
  {
    name: 'audio06',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/九千万 长长久久啊.mp3',
    content: '九千万 长长久久啊',
  },
  {
    name: 'audio07',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/五十万.mp3',
    content: '五十万',
  },
  {
    name: 'audio08',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/似乎我的只牌有用d喔 200w.mp3',
    content: '似乎我的只牌有用d喔 200w',
  },
  {
    name: 'audio09',
    enable: true,
    type: 'dialogue',
    group: ['allin', 'callWhenAllin'],
    src: 'audios/dialogue/你棘手A甘犀利 我晒你浪.mp3',
    content: '你棘手A甘犀利 我晒你浪',
  },
  {
    name: 'audio10',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/几好牌哦 我话5w.mp3',
    content: '几好牌哦 我话5w',
  },
  {
    name: 'audio11',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/十万.mp3',
    content: '十万',
  },
  {
    name: 'audio12',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/咪住 我仲要大.mp3',
    content: '咪住 我仲要大',
  },
  {
    name: 'audio13',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/哼哼哼哼 晒你冷.mp3',
    content: '哼哼哼哼 晒你冷',
  },
  {
    name: 'audio14',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/唔睇底500w.mp3',
    content: '唔睇底500w',
  },
  {
    name: 'audio15',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/大多你500万.mp3',
    content: '大多你500万',
  },
  {
    name: 'audio16',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/大晒你台面果D.mp3',
    content: '大晒你台面果D',
  },
  {
    name: 'audio17',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/好 五百万.mp3',
    content: '好 五百万',
  },
  {
    name: 'audio18',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/好 就大多你八百.mp3',
    content: '好 就大多你八百',
  },
  {
    name: 'audio19',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/就摞三百蚊玩下.mp3',
    content: '就摞三百蚊玩下',
  },
  {
    name: 'audio20',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/就系大你个头.mp3',
    content: '就系大你个头',
  },
  {
    name: 'audio21',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/我show你hand.mp3',
    content: '我show你hand',
  },
  {
    name: 'audio22',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/我又起啤啊 大晒你果D.mp3',
    content: '我又起啤啊 大晒你果D',
  },
  {
    name: 'audio23',
    enable: true,
    type: 'dialogue',
    group: ['allin', 'callWhenAllin'],
    src: 'audios/dialogue/我唔阻人时间啦 晒冷.mp3',
    content: '我唔阻人时间啦 晒冷',
  },
  {
    name: 'audio24',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/我地side bet两百万.mp3',
    content: '我地side bet两百万',
  },
  {
    name: 'audio25',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/我大你500万.mp3',
    content: '我大你500万',
  },
  {
    name: 'audio26',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/我晒你浪 睇晒你.mp3',
    content: '我晒你浪 睇晒你',
  },
  {
    name: 'audio27',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/我睇晒你台面.mp3',
    content: '我睇晒你台面',
  },
  {
    name: 'audio28',
    enable: true,
    type: 'dialogue',
    group: ['allin', 'callWhenAllin'],
    src: 'audios/dialogue/我要同你赌身家.mp3',
    content: '我要同你赌身家',
  },
  {
    name: 'audio29',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/我话事 大晒.mp3',
    content: '我话事 大晒',
  },
  {
    name: 'audio30',
    enable: true,
    type: 'dialogue',
    group: ['allin', 'callWhenAllin'],
    src: 'audios/dialogue/无法子啊 晒浪.mp3',
    content: '无法子啊 晒浪',
  },
  {
    name: 'audio31',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/法国赌神啊嘛 晒你冷.mp3',
    content: '法国赌神啊嘛 晒你冷',
  },
  {
    name: 'audio32',
    enable: true,
    type: 'dialogue',
    group: ['allin', 'callWhenAllin'],
    src: 'audios/dialogue/甘嘛 晒浪啦.mp3',
    content: '甘嘛 晒浪啦',
  },
  {
    name: 'audio33',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/睇咩啊晒你冷.mp3',
    content: '睇咩啊晒你冷',
  },
  {
    name: 'audio34',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/系甘易300w.mp3',
    content: '系甘易300w',
  },
  {
    name: 'audio35',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/跟你30w 大多你100w添.mp3',
    content: '跟你30w 大多你100w添',
  },
  {
    name: 'audio36',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/跟你500w 开黎见我.mp3',
    content: '跟你500w 开黎见我',
  },
  {
    name: 'audio37',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/跟你五十万 再大你一亿.mp3',
    content: '跟你五十万 再大你一亿',
  },
  {
    name: 'audio38',
    enable: true,
    type: 'dialogue',
    group: ['callWhenAllin'],
    src: 'audios/dialogue/跟你晒冷.mp3',
    content: '跟你晒冷',
  },
  {
    name: 'audio39',
    enable: true,
    type: 'dialogue',
    group: ['allin'],
    src: 'audios/dialogue/都唔使问啦系哇 晒冷.mp3',
    content: '都唔使问啦系哇 晒冷',
  },
  {
    name: 'audio40',
    enable: true,
    type: 'dialogue',
    group: ['raise'],
    src: 'audios/dialogue/里铺我买50蚊.mp3',
    content: '里铺我买50蚊',
  },
  {
    name: 'audio41',
    enable: true,
    type: 'dialogue',
    group: ['foldWhenAllin'],
    src: 'audios/dialogue/大家投降输一半济唔济啊.mp3',
    content: '大家投降输一半济唔济啊',
  },
  {
    name: 'audio42',
    enable: true,
    type: 'dialogue',
    group: ['foldWhenAllin'],
    src: 'audios/dialogue/晒住一半先得嘛.mp3',
    content: '晒住一半先得嘛',
  },
  {
    name: 'audio43',
    enable: true,
    type: 'dialogue',
    group: ['foldWhenAllin'],
    src: 'audios/dialogue/小心驶得万年船.mp3',
    content: '小心驶得万年船',
  },
  {
    name: 'audio44',
    enable: true,
    type: 'dialogue',
    group: ['clearCounter'],
    src: 'audios/dialogue/等我拜下哮天犬 屙嘟屎挞死你.mp3',
    content: '等我拜下哮天犬 屙嘟屎挞死你',
  },
  {
    name: 'audio45',
    enable: true,
    type: 'dialogue',
    group: ['clearCounter'],
    src: 'audios/dialogue/等我拜过关二哥 屙嘟尿射死你.mp3',
    content: '等我拜过关二哥 屙嘟尿射死你',
  },
  {
    name: 'audio46',
    enable: true,
    type: 'dialogue',
    group: ['allin', 'callWhenAllin'],
    src: 'audios/dialogue/询众要求啊.mp3',
    content: '询众要求啊',
  },
].map((e) => ({ ...e, src: getStaticSrc(e.src) }));
